// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzcnzprjgeehfghcrcvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6Y256cHJqZ2VlaGZnaGNyY3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODAxMjgsImV4cCI6MjA2NjM1NjEyOH0.w5WOskjTLrKkmUNqTeFOsVDW7Tm7A7ywYsSDKbrIFsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);